/**
 * Created by Administrator on 2016/3/30.
 */
var fmt="yyyy-MM-dd";Date.prototype.Format=function(fmt){//author: meizz 
var o={"M+":this.getMonth()+1,//月份 
"d+":this.getDate(),//日 
"h+":this.getHours(),//小时 
"m+":this.getMinutes(),//分 
"s+":this.getSeconds(),//秒 
"q+":Math.floor((this.getMonth()+3)/3),//季度 
S:this.getMilliseconds()};/(y+)/.test(fmt)&&(fmt=fmt.replace(RegExp.$1,(this.getFullYear()+"").substr(4-RegExp.$1.length)));for(var k in o)new RegExp("("+k+")").test(fmt)&&(fmt=fmt.replace(RegExp.$1,1==RegExp.$1.length?o[k]:("00"+o[k]).substr((""+o[k]).length)));return fmt};var recordsModule=angular.module("records",["ui.router","ui.bootstrap","angularUtils.directives.dirPagination"]);recordsModule.config(["$stateProvider","$urlRouterProvider",function($stateProvider,$urlRouterProvider){$stateProvider.state("checkRecords",{url:"/checkRecords",templateUrl:"/app/modules/records/checkRecords.html"}).state("summaryRecords",{url:"/summaryRecords",templateUrl:"/app/modules/records/summaryRecords.html"}).state("chartRecords",{url:"/chartRecords",templateUrl:"/app/modules/records/chartRecords.html"})}]),recordsModule.controller("checkRecordsCtrl",["$log","$window","$scope","$http","$filter","$sce","$state","$uibModal",function($log,$window,$scope,$http,$filter,$sce,$state,$uibModal){$("#childNameInput").keydown(function(e){var curKey=e.which;return 13==curKey?($scope.searchbycontent(),!1):void 0}),$scope.child={classOfChild:"0",gradeOfChild:"0",childName:""},$scope.paganation={currentPage:1,pageSize:10,totalCount:0},/*有关时间控件的设置-start */
$scope.rangeDate={startDate:(new Date).Format(fmt),endDate:(new Date).Format(fmt)},$scope.getRangeDate=function(){$scope.rangeDate.startDate=$("#startTime").val()?$("#startTime").val():(new Date).Format(fmt),$scope.rangeDate.endDate=$("#endTime").val()?$("#endTime").val():(new Date).Format(fmt)},/*有关时间控件的设置-end */
/*年级班级联动开始*/
$http.post(ssDomain+"admin/grades.json").success(function(response){"undefined"!=typeof response.error?alert("请求参数错误！"):$scope.select1=response.grades}),$scope.selChange=function(id){$http.post(ssDomain+"admin/queryClassList.json",{gradeId:id}).success(function(response){$scope.select2=response.classList})},/*年级班级联动结束*/
/* 导出到excel */
$scope.exportToExcel=function(){$scope.getRangeDate();var param="classOfChild="+$scope.child.classOfChild+"&gradeOfChild="+$scope.child.gradeOfChild+"&childName="+$scope.child.childName+"&startDate="+$scope.rangeDate.startDate+"&endDate="+$scope.rangeDate.endDate;url=ssDomain+"admin/recordsToExcel",$window.location.href=url+"?"+param},$scope.pageChangeHandler=function(num){console.log("going to page "+num),$scope.searchbycontent(num)},/* 条件查选 */
$scope.searchbycontent=function(num){$scope.getRangeDate(),$http.post(ssDomain+"admin/searchRecords.json",{paganation:$scope.paganation,child:$scope.child,rangeDate:$scope.rangeDate}).success(function(response){$scope.recordList=response.data,$scope.paganation.totalCount=null==response.totalNum?0:response.totalNum,$scope.paganation.currentPage=void 0==num?1:num})},$scope.searchbycontent(1)}]),/* 下边是有关记录统计的 */
recordsModule.controller("summaryRecordsCtrl",["$log","$window","$scope","$http","$filter","$sce","$state","$uibModal",function($log,$window,$scope,$http,$filter,$sce,$state,$uibModal){$scope.child={classOfChild:"0",gradeOfChild:"0",childName:""},$scope.paganation={currentPage:1,pageSize:10,totalCount:10},$scope.pageChangeHandler=function(num){$scope.searchbycontent(num)},/*有关时间控件的设置-start */
$scope.rangeDate={startDate:(new Date).Format(fmt),endDate:(new Date).Format(fmt)},$scope.getRangeDate=function(){$scope.rangeDate.startDate=$("#startTime").val()?$("#startTime").val():(new Date).Format(fmt),$scope.rangeDate.endDate=$("#endTime").val()?$("#endTime").val():(new Date).Format(fmt)},/*有关时间控件的设置-end */
/*年级班级联动开始*/
$http.post(ssDomain+"admin/grades.json").success(function(response){"undefined"!=typeof response.error?alert("请求参数错误！"):$scope.select1=response.grades}),$scope.selChange=function(id){$http.post(ssDomain+"admin/queryClassList.json",{gradeId:id}).success(function(response){$scope.select2=response.classList})},/*年级班级联动结束*/
/* 导出到excel */
$scope.exportToExcel=function(){$scope.getRangeDate(),console.log("download excel ");var param="classOfChild="+$scope.child.classOfChild+"&gradeOfChild="+$scope.child.gradeOfChild+"&childName="+$scope.child.childName+"&startDate="+$scope.rangeDate.startDate+"&endDate="+$scope.rangeDate.endDate;url=ssDomain+"admin/summaryRecordsToExcel",$window.location.href=url+"?"+param},/* 条件查选 */
$scope.searchbycontent=function(num){$scope.getRangeDate(),$http.post(ssDomain+"admin/summaryRecords.json",{paganation:$scope.paganation,child:$scope.child,rangeDate:$scope.rangeDate}).success(function(response){$scope.summaryRecordList=response.data,$scope.paganation.totalCount=null==response.totalNum?0:response.totalNum,$scope.paganation.currentPage=void 0==num?0:num})},$scope.searchbycontent(1)}]),/*报表分析controller*/
classModule.controller("chartRecordCtrl",["$scope","$http","$filter","$state","$uibModal",function($scope,$http,$filter,$state,$uibModal){/*年级班级联动开始*/
$http.post(ssDomain+"admin/grades.json").success(function(response){"undefined"!=typeof response.error?alert("请求参数错误！"):$scope.select1=response.grades}),$scope.selChange=function(id){$http.post(ssDomain+"admin/queryClassList.json",{gradeId:id}).success(function(response){$scope.select2=response.classList})},/*年级班级联动结束*/
/*设置报表参数*/
$scope.genOption=function(datas){var width=document.body.clientWidth-300;document.getElementById("chart").style.width=width+"px";for(var x_data=[],y_data=[],i=0;i<datas.length;i++)x_data.push(datas[i].date),y_data.push(datas[i].num);$scope.option={title:{text:"幼儿人数分析报表",x:"center",y:"top"},tooltip:{trigger:"axis",formatter:function(params){var res="";return res+=params[0].name+":",res+="<br/>"+params[0].seriesName+" : "+params[0].value+"人"}},legend:{data:["幼儿人数"],x:"center",y:"bottom"},toolbox:{show:!0,itemSize:24,feature:{saveAsImage:{show:!0,title:"保存为图片",type:"jpeg",lang:["点击本地保存"]}}},xAxis:{data:x_data,axisLabel:{interval:0,rotate:-45,margin:2,textStyle:{color:"#222"}}},yAxis:[{type:"value",axisLabel:{formatter:"{value} 人"}}],series:[{name:"幼儿人数",type:"bar",barWidth:25,data:y_data}]}},
//生成报表信息
$scope.genChart=function(json){var myChart=echarts.init(document.getElementById("chart"));$scope.genOption(json),myChart.setOption($scope.option)},/*分析按钮*/
$scope.analyzer=function(){var startDate=$("#startDate").val(),endDate=$("#endDate").val(),gradeId=$scope.selectMod,classId=$scope.selectMod2;$http.post(ssDomain+"admin/kidCountAnalysis.json",{gradeId:gradeId,classId:classId,startTime:startDate,endTime:endDate}).success(function(response){$scope.genChart(response.records)})},$scope.startTime=curDate.getFullYear()-1+"-"+genMonth(curDate.getMonth()+1),$scope.endTime=curDate.getFullYear()+"-"+genMonth(curDate.getMonth()+1),/*开始加载*/
$http.post(ssDomain+"admin/kidCountAnalysis.json",{startTime:$scope.startTime,endTime:$scope.endTime}).success(function(response){$scope.genChart(response.records)})}]);
/*! xybbGarten 最后修改于： 2016-06-23 */