/**
 * Created by Administrator on 2016/3/30.
 */
var kindModule=angular.module("kindAttendance",["ui.router","ui.bootstrap"]);kindModule.config(["$stateProvider","$urlRouterProvider",function($stateProvider,$urlRouterProvider){$stateProvider.state("chartKindAttendance",{url:"/chartKindAttendance",templateUrl:"/app/modules/kindAttendance/chartKindAttendance.html"})}]),kindModule.controller("chartKindAttendanceCtrl",["$scope","$http","$filter","$state","$uibModal",function($scope,$http,$filter,$state,$uibModal){/*年级班级联动开始*/
$http.post(ssDomain+"admin/grades.json").success(function(response){"undefined"!=typeof response.error?alert("请求参数错误！"):$scope.select1=response.grades}),$scope.selChange=function(id){$http.post(ssDomain+"admin/queryClassList.json",{gradeId:id}).success(function(response){$scope.select2=response.classList})},/*年级班级联动结束*/
/*动态设置报表参数开始*/
$scope.setOption=function(datas,type){//生病服药数
for(var dates=[],levenum=[],attendanceNum=[],sickLeaveNum=[],personalLeaveNum=[],illNum=[],i=0;i<datas.length;i++)dates.push(datas[i].day),levenum.push(datas[i].leaveNum),attendanceNum.push(datas[i].attendanceNum),sickLeaveNum.push(datas[i].sickLeaveNum),personalLeaveNum.push(datas[i].personalLeaveNum),illNum.push(datas[i].illNum);1==type?$scope.options={title:{text:""},tooltip:{trigger:"axis",formatter:function(params){var res=params[0].name+":";return res+="<br/>"+params[0].seriesName+" : "+params[0].value+"人"}},toolbox:{show:!0,itemSize:24,feature:{mark:{show:!1},dataView:{show:!1,readOnly:!1},magicType:{show:!1,type:["line","bar"]},restore:{show:!1},saveAsImage:{show:!0}}},legend:{data:["出勤人数"]},xAxis:{data:dates},yAxis:{type:"value",axisLabel:{formatter:"{value} 人"}},series:[{name:"出勤人数",type:"line",data:attendanceNum,itemStyle:{normal:{label:{show:!0}}}}]}:2==type?$scope.options={title:{text:""},tooltip:{trigger:"axis",formatter:function(params){var res=params[0].name+":";return res+="<br/>"+params[0].seriesName+" : "+params[0].value+"人"}},toolbox:{show:!0,itemSize:24,feature:{mark:{show:!1},dataView:{show:!1,readOnly:!1},magicType:{show:!1,type:["line","bar"]},restore:{show:!1},saveAsImage:{show:!0}}},legend:{data:["请假","病假","事假"]},xAxis:{data:dates},yAxis:{type:"value",axisLabel:{formatter:"{value} 人"}},series:[{name:"请假",type:"line",data:levenum,itemStyle:{normal:{label:{show:!0}}}},{name:"病假",type:"line",data:sickLeaveNum},{name:"事假",type:"line",data:personalLeaveNum}]}:3==type&&($scope.options={title:{text:""},tooltip:{trigger:"axis",formatter:function(params){var res=params[0].name+":";return res+="<br/>"+params[0].seriesName+" : "+params[0].value+"人"}},toolbox:{show:!0,itemSize:24,feature:{mark:{show:!1},dataView:{show:!1,readOnly:!1},magicType:{show:!1,type:["line","bar"]},restore:{show:!1},saveAsImage:{show:!0}}},legend:{data:["生病服药人数"]},xAxis:{data:dates},yAxis:{type:"value",axisLabel:{formatter:"{value} 人"}},series:[{name:"生病服药人数",type:"line",data:illNum,itemStyle:{normal:{label:{show:!0}}}}]})},/*动态设置报表参数结束*/
/*生成报表*/
$scope.genChart=function(type){var myChart=echarts.init(document.getElementById("chart"));$scope.setOption($scope.attendances,type),myChart.setOption($scope.options)},/*选择类型产生不同报表*/
$scope.checkType=function(type){$scope.genChart(type)},/*获取出勤率数据*/
$scope.getAttendance=function(){var year=curDate.getFullYear(),month=genMonth(curDate.getMonth()+1),startDate=(DayNumOfMonth(year,month),year+"-"+month+"-01"),curDay=genDay(curDate.getDate()),endDate=year+"-"+month+"-"+curDay;$scope.startDate=startDate,$scope.endDate=endDate,$http.post(ssDomain+"admin/kidAttendanceAnalysis.json",{startTime:startDate,endTime:endDate}).success(function(response){$scope.attendances=response.records,$scope.genChart(1),$scope.type=1})},$scope.getAttendance(),/*点击分析按钮*/
$scope.analyzer=function(){var startDate=$scope.startDate,endDate=$scope.endDate,gradeId=$scope.selectMod,classId=$scope.selectMod2,type=$scope.type;$http.post(ssDomain+"admin/kidAttendanceAnalysis.json",{startTime:startDate,endTime:endDate,gradeId:gradeId,classId:classId}).success(function(response){$scope.attendances=response.records,$scope.genChart(type)})}}]);
/*! xybbGarten 最后修改于： 2016-06-23 */