/**
 * Created by ywg on 2016/4/25.
 * function:添加处理小问号逻辑
 * desc：
 *      questionMarkCtrl处理小问号管理controller
 *      chart_qsMarkCtrl处理小问号报表统计controller
 */
var questionMarkModule=angular.module("questionMark",["ui.router","ui.bootstrap","angularUtils.directives.dirPagination"]);questionMarkModule.config(["$stateProvider","$urlRouterProvider",function($stateProvider,$urlRouterProvider){$stateProvider.state("questionMark",{url:"/questionMark",templateUrl:"/app/modules/questionMark/questionMark.html"}).state("chart_questionMark",{url:"/chart_questionMark",templateUrl:"/app/modules/questionMark/chart_questionMark.html"})}]),questionMarkModule.controller("questionMarkCtrl",function($scope,$http){function getQuestionMarkTypeList(){var req={method:"POST",url:ssDomain+"admin/showQuestionTypes.json"};$http(req).then(function(result){$scope.questionMarkTypeList=result.data.questionTypes})}function getResultsPage(pageNumber){var req={method:"POST",url:ssDomain+"admin/questionMarkList.json",data:{gradeId:$scope.gradeId,classId:$scope.classId,questionMarkType:$scope.questionMarkTypeId,pageSize:$scope.pageSize,pageNo:pageNumber}};$http(req).then(function(result){$scope.questionMarkClassList=result.data.questionMarkClassList,$scope.totalCount=result.data.totalCount})}$scope.pageSize=10,$scope.totalCount=0,getResultsPage(1),$scope.pageNo=1,getQuestionMarkTypeList(),$scope.pageChanged=function(newPage){getResultsPage(newPage)},$http.post(ssDomain+"admin/grades.json").success(function(response){$scope.gradeList=response.grades}),$scope.selChange=function(id){$http.post(ssDomain+"admin/queryClassList.json",{gradeId:id}).success(function(response){$scope.classList=response.classList})},
//导出
$scope.exportToExcel=function(){var params="gradeId="+$scope.gradeId+"&classId="+$scope.classId+"&questionMarkType="+$scope.questionMarkTypeId;url=ssDomain+"admin/exportQuestionMark",window.location.href=url+"?"+params},
//查询
$scope.query=function(){getResultsPage(1)}}),questionMarkModule.controller("chart_qsMarkCtrl",function($scope,$http){/*年级班级联动开始*/
$http.post(ssDomain+"admin/grades.json").success(function(response){"undefined"!=typeof response.error?alert("请求参数错误！"):$scope.gradelist=response.grades}),$scope.selChange=function(id){$http.post(ssDomain+"admin/queryClassList.json",{gradeId:id}).success(function(response){$scope.classlist=response.classList})},/*获取发布问题的时间*/
$http.post(ssDomain+"admin/dateList.json").success(function(response){if("undefined"!=typeof response.error)alert("请求参数错误！");else{for(var dtList=[],srcList=response.dateList,i=0;i<srcList.length;i++){var dObj={};dObj.checked=0==i,dObj.date=srcList[i],dtList.push(dObj)}$scope.pubDateList=dtList}}),$scope.selDate=function(date){$http.post(ssDomain+"admin/questionMarkAnalysis.json",{gradeId:$scope.gradeId,classId:$scope.classId,createTime:date}).success(function(response){for(var dtList=[],srcList=response.questionMarkClassList,i=0;i<srcList.length;i++){var dObj={};dObj.checked=0==i,dObj.date=srcList[i],dtList.push(dObj)}$scope.qsList=dtList})},$scope.analyzer=function(){var qsid=$scope.qsId,gradeId=$scope.gradeId,classId=$scope.classId;$http.post(ssDomain+"admin/questionMarkAnalysis.json",{gradeId:gradeId,classId:classId,createTime:$scope.publishDate,questionMarkId:qsid}).success(function(response){genChart(response.questionMarkClassList,"bar")})};var getMarkTypeList=function(){var req={method:"POST",url:ssDomain+"admin/showQuestionTypes.json"};$http(req).then(function(result){$scope.qsMarkTypeList=result.data.questionTypes})};getMarkTypeList();var genChart=function(jsData,type){for(var qsList=jsData,myChart=echarts.init(document.getElementById("chart")),titleName=jsData[0].title,classData=[],yesNums=[],noNums=[],i=0;i<qsList.length;i++){var item=qsList[i];classData.push(item.className),yesNums.push(item.yesCount),noNums.push(item.noCount)}var option={title:{text:"小问号问题："+titleName,x:"center",y:"top"},tooltip:{trigger:"axis",axisPointer:{type:"shadow"}},grid:{left:"3%",right:"4%",bottom:"8%",containLabel:!0},legend:{data:["可以","不可以"],x:"center",y:"bottom"},xAxis:{type:"value",boundaryGap:[0,.01]},yAxis:{type:"category",data:classData,splitLine:{show:!1}},series:[]},yesItem={name:"可以",type:type,itemStyle:{normal:{label:{show:!0,position:"right"}}},barGap:1,barWidth:18,data:yesNums},noItem={name:"不可以",type:type,itemStyle:{normal:{label:{show:!0,position:"right"}}},barGap:1,barWidth:18,data:noNums};option.series.push(yesItem),option.series.push(noItem),myChart.setOption(option)}});
/*! xybbGarten 最后修改于： 2016-06-23 */