var studentEveningModule=angular.module("studentEvening",["ui.router","ui.bootstrap","angularUtils.directives.dirPagination"]);studentEveningModule.config(["$stateProvider","$urlRouterProvider",function($stateProvider,$urlRouterProvider){$stateProvider.state("studentEvening",{url:"/studentEvening",templateUrl:"/app/modules/studentEvening/studentEvening.html"}).state("studentEveningSummary",{url:"/studentEveningSummary",templateUrl:"/app/modules/studentEvening/studentEveningSummary.html"})}]),studentEveningModule.controller("studentEveningCtrl",function($scope,$http){function getResultsPage(pageNumber){var startTime=$("#startTime").val()?$("#startTime").val():(new Date).Format(fmt),endTime=$("#endTime").val()?$("#endTime").val():(new Date).Format(fmt),req={method:"POST",url:ssDomain+"admin/studentEveningList.json",data:{gradeId:$scope.gradeId,classId:$scope.classId,startTime:startTime,endTime:endTime,studentName:$scope.studentName,pageSize:$scope.pageSize,pageNo:pageNumber}};$http(req).then(function(result){$scope.studentEveningList=result.data.studentEveningList,$scope.totalCount=result.data.totalCount})}$scope.pageSize=10,$scope.totalCount=0,$scope.createTime=(new Date).Format(fmt),$scope.beginTime=(new Date).Format(fmt),$scope.endTime=(new Date).Format(fmt),getResultsPage(1),$scope.pageNo=1,$("#studentNameInput").keydown(function(e){var curKey=e.which;return 13==curKey?($scope.query(),!1):void 0}),$scope.pageChanged=function(newPage){getResultsPage(newPage)},$http.post(ssDomain+"admin/grades.json").success(function(response){$scope.gradeList=response.grades}),$scope.selChange=function(id){$http.post(ssDomain+"admin/queryClassList.json",{gradeId:id}).success(function(response){$scope.classList=response.classList})},
//导出
$scope.exportToExcel=function(){var startTime=$("#startTime").val(),endTime=$("#endTime").val(),params="gradeId="+$scope.gradeId+"&classId="+$scope.classId+"&startTime="+startTime+"&endTime="+endTime;url=ssDomain+"admin/exportStudentEvening",window.location.href=url+"?"+params},
//查询
$scope.query=function(){getResultsPage(1)}}),studentEveningModule.controller("studentEveningSummaryCtrl",function($scope,$http){function getResultsPage(pageNumber){var startTime=$("#startTime").val()?$("#startTime").val():(new Date).Format(fmt),endTime=$("#endTime").val()?$("#endTime").val():(new Date).Format(fmt),req={method:"POST",url:ssDomain+"admin/studentEveningSummList.json",data:{gradeId:$scope.gradeId,classId:$scope.classId,startTime:startTime,endTime:endTime,pageSize:$scope.pageSize,pageNo:pageNumber}};$http(req).then(function(result){$scope.studentEveningList=result.data.studentEveningList})}$scope.pageSize=10,// this should match however many results your API puts on one page
$scope.beginTime=(new Date).Format(fmt),$scope.endTime=(new Date).Format(fmt),getResultsPage(1),$scope.pageNo=1,$scope.totalCount=0,$scope.pageChanged=function(newPage){getResultsPage(newPage)},$http.post(ssDomain+"admin/grades.json").success(function(response){$scope.gradeList=response.grades}),$scope.selChange=function(id){$http.post(ssDomain+"admin/queryClassList.json",{gradeId:id}).success(function(response){$scope.classList=response.classList})},
//导出
$scope.exportToExcel=function(){var startTime=$("#startTime").val(),endTime=$("#endTime").val(),params="gradeId="+$scope.gradeId+"&classId="+$scope.classId+"&startTime="+startTime+"&endTime="+endTime;url=ssDomain+"admin/exportStudentEveningSumm",window.location.href=url+"?"+params},
//查询
$scope.query=function(){getResultsPage(1)}});
/*! xybbGarten 最后修改于： 2016-06-23 */