/**
 * Created by Administrator on 2016/3/30.
 */
var recordsModule=angular.module("favoriteActivity",["ui.router","ui.bootstrap","angularUtils.directives.dirPagination"]);recordsModule.config(["$stateProvider","$urlRouterProvider",function($stateProvider,$urlRouterProvider){$stateProvider.state("favoriteActivityCheckRecords",{url:"/favoriteActivityCheckRecords",templateUrl:"/app/modules/favoriteActivity/checkRecords.html"}).state("favoriteActivitySummaryRecords",{url:"/favoriteActivitySummaryRecords",templateUrl:"/app/modules/favoriteActivity/summaryRecords.html"}).state("chartActivity",{url:"/charActivity",templateUrl:"/app/modules/favoriteActivity/chartActivity.html"})}]),recordsModule.controller("favoriteActivityCheckRecordsCtrl",["$log","$window","$scope","$http","$filter","$sce","$state","$uibModal",function($log,$window,$scope,$http,$filter,$sce,$state,$uibModal){$("#childName").keydown(function(e){var curKey=e.which;return 13==curKey?($scope.searchbycontent(),!1):void 0}),$scope.child={classOfChild:"0",gradeOfChild:"0",childName:""},$scope.paganation={currentPage:1,pageSize:10,totalCount:0},/* 年级班级联动开始 */
$http.post(ssDomain+"admin/grades.json").success(function(response){"undefined"!=typeof response.error?alert("请求参数错误！"):$scope.select1=response.grades}),$scope.selChange=function(id){$http.post(ssDomain+"admin/queryClassList.json",{gradeId:id}).success(function(response){$scope.select2=response.classList})},/* 年级班级联动结束 */
/* 有关时间控件的设置-start */
$scope.rangeDate={startDate:(new Date).Format(fmt),endDate:(new Date).Format(fmt)},$scope.getRangeDate=function(){$scope.rangeDate.startDate=$("#startTime").val()?$("#startTime").val():(new Date).Format(fmt),$scope.rangeDate.endDate=$("#endTime").val()?$("#endTime").val():(new Date).Format(fmt)},/* 导出到excel */
$scope.exportToExcel=function(){$scope.getRangeDate(),
// 后端访问地址
console.log("download excel ");var param="classOfChild="+$scope.child.classOfChild+"&gradeOfChild="+$scope.child.gradeOfChild+"&childName="+$scope.child.childName+"&startDate="+$scope.rangeDate.startDate+"&endDate="+$scope.rangeDate.endDate;url=ssDomain+"admin/favoriteRecordsToExcel",$window.location.href=url+"?"+param},$scope.pageChangeHandler=function(num){if(console.log("going to page "+num),1==num)$scope.searchbycontent();else{//当选择不是第一页的时候用页面级别的缓存
var currentnum=(num-1)*$scope.paganation.pageSize,response=$scope.frecordAll,result=[],i=0;for(var item in response)i>currentnum&&result.push(response[item]),i++;$scope.frecordList=result}},/* 条件查选 */
$scope.searchbycontent=function(inclass){$scope.getRangeDate(),/* 获取列表 */
$http.post(ssDomain+"admin/searchFavoriteRecords.json",{paganation:$scope.paganation,child:$scope.child,rangeDate:$scope.rangeDate}).success(function(response){$scope.frecordList=response,$scope.frecordAll=response;var i=0;for(var item in response)$scope.biaoti=response[item],i++;$scope.paganation.totalCount=i})},$scope.searchbycontent()}]),/* 下边是有关记录统计的 */
recordsModule.controller("favoriteActivitySummaryCtrl",["$log","$window","$scope","$http","$filter","$sce","$state","$uibModal",function($log,$window,$scope,$http,$filter,$sce,$state,$uibModal){$scope.child={classOfChild:"0",gradeOfChild:"0",childName:""},$scope.paganation={currentPage:1,pageSize:10,totalCount:0},/* 年级班级联动开始 */
$http.post(ssDomain+"admin/grades.json").success(function(response){"undefined"!=typeof response.error?alert("请求参数错误！"):$scope.select1=response.grades}),$scope.selChange=function(id){$http.post(ssDomain+"admin/queryClassList.json",{gradeId:id}).success(function(response){$scope.select2=response.classList})},/* 年级班级联动结束 */
/* 有关时间控件的设置-start */
$scope.rangeDate={startDate:(new Date).Format(fmt),endDate:(new Date).Format(fmt)},$scope.getRangeDate=function(){$scope.rangeDate.startDate=$("#startTime").val()?$("#startTime").val():(new Date).Format(fmt),$scope.rangeDate.endDate=$("#endTime").val()?$("#endTime").val():(new Date).Format(fmt)},/* 导出到excel */
$scope.exportToExcel=function(){$scope.getRangeDate(),
// 后端访问地址
// 后端访问地址
console.log("download excel ");var param="classOfChild="+$scope.child.classOfChild+"&gradeOfChild="+$scope.child.gradeOfChild+"&childName="+$scope.child.childName+"&startDate="+$scope.rangeDate.startDate+"&endDate="+$scope.rangeDate.endDate;url=ssDomain+"admin/summaryFavoriteRecordsToExcel",$window.location.href=url+"?"+param},/* 条件查选 */
$scope.searchbycontent=function(){$scope.getRangeDate(),/* 获取列表 */
$http.post(ssDomain+"admin/summaryFavoriteRecords.json",{paganation:$scope.paganation,child:$scope.child,rangeDate:$scope.rangeDate}).success(function(response){$scope.summaryRecordList=response.data;for(var item in response.data)$scope.banjibiaoti=response.data[item];$scope.summaryRecordAllList=response.dataAll,$scope.paganation.totalCount=response.totalCount})},$scope.searchbycontent()}]),/* 报表分析controller */
classModule.controller("chartActivityCtrl",["$scope","$http","$filter","$state","$uibModal",function($scope,$http,$filter,$state,$uibModal){/*第一次清求页面默认显示一年数据*/
$scope.startTime=curDate.getFullYear()-1+"-"+genMonth(curDate.getMonth()+1),$scope.endTime=curDate.getFullYear()+"-"+genMonth(curDate.getMonth()+1),$scope.selActivitys=[],/*最喜爱活动列表*/
$http.post(ssDomain+"admin/listActivitys.json").success(function(response){if("undefined"!=typeof response.error)alert("请求参数错误！");else{var list=response.activitys;if(null==list)return;for(var i=0;i<list.length;i++)"晚餐活动"!=list[i].activityName&&"户外活动"!=list[i].activityName||(list[i].checked=!0,$scope.selActivitys.push(list[i].id));$scope.activitys=response.activitys,$http.post(ssDomain+"admin/kidLovingActAnalysis.json",{activities:$scope.selActivitys,startTime:$scope.startTime,endTime:$scope.endTime}).success(function(response){"undefined"!=typeof response.error?layer.alert("请求参数错误!",{icon:0}):$scope.genChart(response.records)})}}),/*年级班级联动开始*/
$http.post(ssDomain+"admin/grades.json").success(function(response){"undefined"!=typeof response.error?alert("请求参数错误！"):$scope.select1=response.grades}),$scope.selChange=function(id){$http.post(ssDomain+"admin/queryClassList.json",{gradeId:id}).success(function(response){$scope.select2=response.classList})},/*年级班级联动结束*/
/*设置数据*/
$scope.setOption=function(datas){var width=document.body.clientWidth-300;document.getElementById("chart").style.width=width+"px";for(var legends=[],serie=[],x_data=[],i=0;i<datas.length;i++){legends.push(datas[i].activityName);for(var d=[],j=0;j<datas[i].data.length;j++)d.push(datas[i].data[j].rate),x_data.push(datas[i].data[j].month);var json={name:datas[i].activityName,type:"line",data:d};serie.push(json)}$scope.option={title:{text:"幼儿喜爱活动分析报表",x:"center",y:"top"},toolbox:{show:!0,itemSize:24,feature:{saveAsImage:{show:!0}}},legend:{data:legends,orient:"vertical",x:"right",y:"center"},xAxis:{data:x_data,axisLabel:{interval:0,margin:2,textStyle:{color:"#222"}}},yAxis:{axisLabel:{formatter:"{value}%"}},series:serie}},/*生成报表*/
$scope.genChart=function(datas){var myChart=echarts.init(document.getElementById("chart"));$scope.setOption(datas),myChart.setOption($scope.option)},/*多选框单击按钮*/
$scope.check=function(act){act.checked?act.checked=!0:act.checked=!1},/*分析按钮时间*/
$scope.analyzer=function(){for(var activityIds=[],list=$scope.activitys,i=0;i<list.length;i++)list[i].checked&&activityIds.push(list[i].id);var startDate=$("#startDate").val(),endDate=$("#endDate").val(),gradeId=$scope.selectMod,classId=$scope.selectMod2;$http.post(ssDomain+"admin/kidLovingActAnalysis.json",{activities:activityIds,gradeId:gradeId,classId:classId,startTime:startDate,endTime:endDate}).success(function(response){$scope.genChart(response.records)})}}]);
/*! xybbGarten 最后修改于： 2016-06-23 */